johnnys = Restaurant.find_or_create_by(name: "Johnnys")
maggies = Restaurant.find_or_create_by(name: "Maggies")
pauls = Restaurant.find_or_create_by(name: "Pauls")
mikes = Restaurant.find_or_create_by(name: "Mikes")
casablanca = Restaurant.find_or_create_by(name: "Casablanca")
ricks_cafe = Restaurant.find_or_create_by(name: "Rick's Cafe")
el_diablo = Restaurant.find_or_create_by(name: "El Diable")
ms_shirleys = Restaurant.find_or_create_by(name: "Miss Shirleys")
half_time = Restaurant.find_or_create_by(name: "Half Time")
dublin = Restaurant.find_or_create_by(name: "Dublin")
normas = Restaurant.find_or_create_by(name: "Normas")
raw = Restaurant.find_or_create_by(name: "Raw")
lockhart = Restaurant.find_or_create_by(name: "Lockhart")
safehouse = Restaurant.find_or_create_by(name: "Safehouse")
elbow_room = Restaurant.find_or_create_by(name: "Elbow Room")
napa_valley = Restaurant.find_or_create_by(name: "Napa Valley")
tommy_guns = Restaurant.find_or_create_by(name: "Tommy Guns")
burger_house = Restaurant.find_or_create_by(name: "Burger House")
chadwicks = Restaurant.find_or_create_by(name: "Chadwick's")
volas = Restaurant.find_or_create_by(name: "Vola's")
mcdonalds = Restaurant.find_or_create_by(name: "McDonald's")



burger = Dish.find_or_create_by(name: "Burger")
oyster = Dish.find_or_create_by(name: "Oyster")
fries = Dish.find_or_create_by(name: "Fries")
dolma = Dish.find_or_create_by(name: "Dolma")
apple_pie = Dish.find_or_create_by(name: "Apple Pie")
onion_rings = Dish.find_or_create_by(name: "Onion Rings")
chicken_wings = Dish.find_or_create_by(name: "Chicken Wings")
pizza = Dish.find_or_create_by(name: "Pizza")
couscous = Dish.find_or_create_by(name: "Couscous")
beef_tips = Dish.find_or_create_by(name: "Beef Tips")
fried_chicken = Dish.find_or_create_by(name: "Fried Chicken")
asparagus = Dish.find_or_create_by(name: "Asparagus")
spaghetti = Dish.find_or_create_by(name: "Spaghetti")
squid = Dish.find_or_create_by(name: "Squid")
ceviche = Dish.find_or_create_by(name: "Ceviche")
tartare = Dish.find_or_create_by(name: "Tartare")
empanada = Dish.find_or_create_by (name: "Empanada")


spicy = Tag.find_or_create_by(name: "Spicy")
vegetarian = Tag.find_or_create_by(name: "Vegetarian")
gluten_free = Tag.find_or_create_by(name: "Gluten Free")
organic = Tag.find_or_create_by(name: "Organic")
dairy_free = Tag.find_or_create_by(name: "Dairy Free")
nut_allergy = Tag.find_or_create_by(name: "Nut Allergy")
free_range = Tag.find_or_create_by(name: "Free Range")
alliums = Tag.find_or_create_by(name: "Alliums")
vegan = Tag.find_or_create_by(name: "Vegan")
chefs_special = Tag.find_or_create_by(name: "Chef's Special")
raw_food = Tag.find_or_create_by(name: "Raw Food")